apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi # Up to 1 GB of vulme
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMane
    # - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate